DROP DATABASE IF EXISTS bookdb2;
DROP USER IF EXISTS `bookdb2admin`@`%`;
DROP USER IF EXISTS `bookdb2user`@`%`;

CREATE DATABASE IF NOT EXISTS bookdb2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `bookdb2admin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bookdb2`.* TO `bookdb2admin`@`%`;

CREATE USER IF NOT EXISTS `bookdb2user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';

GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `bookdb2`.* TO `bookdb2user`@`%`;

FLUSH PRIVILEGES;